// SPDX-License-Identifier: ISC
//
//! Tests for the air-gap package and the trustless-review logic — the security
//! core of the format. Covers: CBOR round-trip + version gating, ownership
//! classification (change vs recipient vs mislabelled-change), pre-sign input
//! validation, end-to-end signing self-consistency, and the anti-tamper
//! prev_script tripwire.

#![cfg(all(feature = "airgap", feature = "mnemonic"))]

use dcr_rs::address::p2pkh_script;
use dcr_rs::airgap::{
    decode_sign_request, encode_sign_request, sign_request, InputMeta, OutputMeta, SignRequest,
    FORMAT_VERSION,
};
use dcr_rs::hashing::hash160;
use dcr_rs::hd::{ExtPrivKey, ExtPubKey, BRANCH_EXTERNAL};
use dcr_rs::secp256k1::{ecdsa::Signature, Message, PublicKey, Secp256k1};
use dcr_rs::sighash::signature_hash_all;
use dcr_rs::tx::MsgTx;
use dcr_rs::{Error, Network};

const ENTROPY_HEX: &str = "348360ae0a69b1883b0dfc060136108dfcabe9f4bf8af3e866b742fb53f1caa5";

fn master() -> ExtPrivKey {
    let entropy = hex::decode(ENTROPY_HEX).unwrap();
    ExtPrivKey::from_entropy(&entropy, "", Network::Mainnet).unwrap()
}

fn account_pub(secp: &Secp256k1<dcr_rs::secp256k1::All>, m: &ExtPrivKey) -> ExtPubKey {
    m.account_key(secp, 0).unwrap().neuter(secp)
}

/// A 25-byte P2PKH script that is NOT ours (arbitrary hash160).
fn foreign_script(tag: u8) -> Vec<u8> {
    p2pkh_script(&[tag; 20]).to_vec()
}

fn basic_request(prev_script: Vec<u8>, outputs: Vec<OutputMeta>) -> SignRequest {
    SignRequest {
        format_version: FORMAT_VERSION,
        tx_version: 1,
        account: 0,
        lock_time: 0,
        expiry: 0,
        inputs: vec![InputMeta {
            prev_hash: [9u8; 32],
            prev_index: 0,
            tree: 0,
            sequence: 0xffff_ffff,
            value_in: 100_000,
            branch: 0,
            index: 0,
            prev_script,
        }],
        outputs,
    }
}

#[test]
fn cbor_roundtrip_and_version_gate() {
    let req = basic_request(
        foreign_script(0xaa),
        vec![OutputMeta {
            value: 12000,
            version: 0,
            pk_script: foreign_script(0xbb),
            is_change: false,
        }],
    );
    let bytes = encode_sign_request(&req).unwrap();
    let back = decode_sign_request(&bytes).unwrap();
    assert_eq!(back.inputs.len(), 1);
    assert_eq!(back.outputs[0].value, 12000);
    assert_eq!(back.inputs[0].value_in, 100_000);

    // A package declaring an unknown FORMAT_VERSION must be rejected.
    let mut bad = req;
    bad.format_version = FORMAT_VERSION + 1;
    let bad_bytes = encode_sign_request(&bad).unwrap();
    assert!(matches!(
        decode_sign_request(&bad_bytes),
        Err(Error::UnsupportedVersion)
    ));
}

/// Golden bytes generated by the KeyOS `decred-core` encoder for this exact
/// request. The format is shared across devices, so dcr-rs must reproduce it
/// byte for byte — any drift here breaks companion-wallet interop.
#[test]
fn cbor_layout_matches_keyos_golden_bytes() {
    const GOLDEN_HEX: &str = "87010100001a000679328188982007070707070707070707070707070707\
                              0707070707070707070707070707070701001affffffff1a075bcd150005\
                              86187618a91418aa188818ac81841a05f5e1000086187618a91418bb1888\
                              18acf5";
    let req = SignRequest {
        format_version: FORMAT_VERSION,
        tx_version: 1,
        account: 0,
        lock_time: 0,
        expiry: 424242,
        inputs: vec![InputMeta {
            prev_hash: [7u8; 32],
            prev_index: 1,
            tree: 0,
            sequence: 0xffff_ffff,
            value_in: 123_456_789,
            branch: 0,
            index: 5,
            prev_script: vec![0x76, 0xa9, 0x14, 0xaa, 0x88, 0xac],
        }],
        outputs: vec![OutputMeta {
            value: 100_000_000,
            version: 0,
            pk_script: vec![0x76, 0xa9, 0x14, 0xbb, 0x88, 0xac],
            is_change: true,
        }],
    };
    let golden: String = GOLDEN_HEX.split_whitespace().collect();
    assert_eq!(hex::encode(encode_sign_request(&req).unwrap()), golden);

    let back = decode_sign_request(&hex::decode(golden).unwrap()).unwrap();
    assert_eq!(back.expiry, 424242);
    assert_eq!(back.inputs[0].index, 5);
    assert!(back.outputs[0].is_change);
}

#[test]
fn review_owned_classifies_change_recipient_and_mislabel() {
    let secp = Secp256k1::new();
    let m = master();
    let acct = m.account_key(&secp, 0).unwrap();

    // Our own change address (account 0, external/3) — device should recognize
    // it as change regardless of the companion's flag.
    let own = acct.address_key(&secp, BRANCH_EXTERNAL, 3).unwrap();
    let own_script = p2pkh_script(&hash160(&own.compressed_pubkey(&secp))).to_vec();

    let mut req = basic_request(
        own_script.clone(),
        vec![
            // Owned, but companion DIDN'T flag it as change — device must still
            // count it as change (it pays us).
            OutputMeta {
                value: 1_000,
                version: 0,
                pk_script: own_script,
                is_change: false,
            },
            // Genuine external recipient.
            OutputMeta {
                value: 5_000,
                version: 0,
                pk_script: foreign_script(0xcc),
                is_change: false,
            },
            // Foreign address the companion LIED about (claimed change). This is
            // the attack the trustless review exists to catch.
            OutputMeta {
                value: 2_000,
                version: 0,
                pk_script: foreign_script(0xdd),
                is_change: true,
            },
        ],
    );
    req.inputs[0].value_in = 10_000;

    let summary = req.review_owned(&secp, &account_pub(&secp, &m)).unwrap();
    let change_total: i64 = summary.change.iter().map(|c| c.1).sum();
    assert_eq!(change_total, 1_000, "only the owned output is change");
    assert_eq!(
        summary.recipients.len(),
        2,
        "both foreign outputs are recipients"
    );
    assert_eq!(
        summary.flagged_mismatches.len(),
        1,
        "the mislabelled output is flagged"
    );
    assert_eq!(summary.flagged_mismatches[0].1, 2_000);
    assert_eq!(summary.fee, 10_000 - (1_000 + 5_000 + 2_000));

    // Recipient addresses render as mainnet strings.
    assert!(summary.recipients.iter().all(|r| r.0.starts_with("Ds")));
}

#[test]
fn check_owned_inputs_accepts_our_own_and_rejects_tampering() {
    let secp = Secp256k1::new();
    let m = master();
    let acct = m.account_key(&secp, 0).unwrap();
    let account = account_pub(&secp, &m);

    let key0 = acct.address_key(&secp, BRANCH_EXTERNAL, 0).unwrap();
    let script0 = p2pkh_script(&hash160(&key0.compressed_pubkey(&secp))).to_vec();
    let outputs = vec![OutputMeta {
        value: 90_000,
        version: 0,
        pk_script: foreign_script(0xee),
        is_change: false,
    }];

    // A well-formed request from a correct companion passes.
    let good = basic_request(script0.clone(), outputs.clone());
    good.check_owned_inputs(&secp, &account).unwrap();

    // prev_script not re-derivable from our key → tripwire.
    let evil = basic_request(foreign_script(0x11), outputs.clone());
    assert_eq!(
        evil.check_owned_inputs(&secp, &account),
        Err(Error::ScriptMismatch)
    );

    // Stake-tree input, unknown branch, absurd fee: all structurally invalid.
    let mut bad = basic_request(script0.clone(), outputs.clone());
    bad.inputs[0].tree = 1;
    assert!(matches!(
        bad.check_owned_inputs(&secp, &account),
        Err(Error::InvalidRequest(_))
    ));

    let mut bad = basic_request(script0.clone(), outputs.clone());
    bad.inputs[0].branch = 2;
    assert!(matches!(
        bad.check_owned_inputs(&secp, &account),
        Err(Error::InvalidRequest(_))
    ));

    let mut bad = basic_request(script0, outputs);
    bad.outputs[0].value = 200_000; // exceeds the 100_000 input
    assert!(matches!(
        bad.check_owned_inputs(&secp, &account),
        Err(Error::InvalidRequest(_))
    ));
}

#[test]
fn sign_request_is_self_consistent_and_low_s() {
    let secp = Secp256k1::new();
    let m = master();
    let acct = m.account_key(&secp, 0).unwrap();
    let key0 = acct.address_key(&secp, BRANCH_EXTERNAL, 0).unwrap();
    let pk0 = key0.compressed_pubkey(&secp);
    let script0 = p2pkh_script(&hash160(&pk0)).to_vec();

    let req = basic_request(
        script0.clone(),
        vec![OutputMeta {
            value: 90_000,
            version: 0,
            pk_script: foreign_script(0xee),
            is_change: false,
        }],
    );

    let signed = sign_request(&secp, &m, &req).unwrap();
    let tx = MsgTx::parse_full(&signed).unwrap();

    // Extract sig + pubkey from the produced sigScript and verify it against the
    // sighash we recompute — proves sign and sighash agree end to end.
    let ss = &tx.tx_in[0].signature_script;
    let l1 = ss[0] as usize;
    let hashtype = ss[l1]; // last byte of the first push
    let der = &ss[1..l1];
    let l2 = ss[1 + l1] as usize;
    let pubkey = &ss[2 + l1..2 + l1 + l2];
    assert_eq!(hashtype, 0x01, "SigHashAll");
    assert_eq!(pubkey, &pk0[..], "signs with the re-derived key");

    let sighash = signature_hash_all(&tx, 0, &script0).unwrap();
    let mut sig = Signature::from_der(der).unwrap();
    let pk = PublicKey::from_slice(pubkey).unwrap();
    secp.verify_ecdsa(&Message::from_digest(sighash), &sig, &pk)
        .expect("self-produced signature verifies");

    // Already low-S, so normalizing is a no-op (consensus requires canonical S).
    let before = sig;
    sig.normalize_s();
    assert_eq!(before, sig, "signature is already low-S");
}

#[test]
fn check_owned_inputs_refuses_hostile_amounts() {
    let secp = Secp256k1::new();
    let m = master();
    let account = account_pub(&secp, &m);
    let key0 = m
        .account_key(&secp, 0)
        .unwrap()
        .address_key(&secp, BRANCH_EXTERNAL, 0)
        .unwrap();
    let script0 = p2pkh_script(&hash160(&key0.compressed_pubkey(&secp))).to_vec();
    let outputs = vec![OutputMeta {
        value: 90_000,
        version: 0,
        pk_script: foreign_script(0xee),
        is_change: false,
    }];

    // Single amount above max supply.
    let mut bad = basic_request(script0.clone(), outputs.clone());
    bad.inputs[0].value_in = dcr_rs::airgap::MAX_ATOMS + 1;
    assert!(matches!(
        bad.check_owned_inputs(&secp, &account),
        Err(Error::InvalidRequest(_))
    ));

    // Two i64::MAX outputs wrap a naive i64 sum to negative, which would
    // sneak past a wrapping fee check; the exact-sum comparison plus the
    // per-amount cap must both refuse.
    let mut bad = basic_request(script0, outputs);
    bad.outputs = alloc_two_huge_outputs();
    assert!(matches!(
        bad.check_owned_inputs(&secp, &account),
        Err(Error::InvalidRequest(_))
    ));
    // The public totals saturate rather than wrapping negative.
    assert_eq!(bad.output_total(), i64::MAX);
}

fn alloc_two_huge_outputs() -> Vec<OutputMeta> {
    let huge = |tag| OutputMeta {
        value: i64::MAX,
        version: 0,
        pk_script: foreign_script(tag),
        is_change: false,
    };
    vec![huge(0xaa), huge(0xbb)]
}

#[test]
fn sign_request_refuses_out_of_schema_paths() {
    let secp = Secp256k1::new();
    let m = master();
    let outputs = vec![OutputMeta {
        value: 90_000,
        version: 0,
        pk_script: foreign_script(0xee),
        is_change: false,
    }];

    // Even without check_owned_inputs, the signer itself must refuse
    // non-wallet branches, hardened indices, and stake-tree inputs.
    let mut req = basic_request(foreign_script(0x11), outputs.clone());
    req.inputs[0].branch = 2;
    assert!(matches!(
        sign_request(&secp, &m, &req),
        Err(Error::InvalidRequest(_))
    ));

    let mut req = basic_request(foreign_script(0x11), outputs.clone());
    req.inputs[0].index = 0x8000_0000;
    assert!(matches!(
        sign_request(&secp, &m, &req),
        Err(Error::InvalidRequest(_))
    ));

    let mut req = basic_request(foreign_script(0x11), outputs);
    req.inputs[0].tree = 1;
    assert!(matches!(
        sign_request(&secp, &m, &req),
        Err(Error::InvalidRequest(_))
    ));
}

#[test]
fn sign_request_refuses_prev_script_mismatch() {
    let secp = Secp256k1::new();
    let m = master();

    // prev_script claims a different address than the key at branch/index owns:
    // the anti-tamper tripwire must fire instead of signing.
    let req = basic_request(
        foreign_script(0x11), // not the script for m/44'/42'/0'/0/0
        vec![OutputMeta {
            value: 90_000,
            version: 0,
            pk_script: foreign_script(0xee),
            is_change: false,
        }],
    );

    assert_eq!(sign_request(&secp, &m, &req), Err(Error::ScriptMismatch));
}
